name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.gpgmail }} bundle

    if: "!contains(github.event.head_commit.message, '[no-build]')"

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        gpgmail: [GPGMail_3, GPGMail_4, GPGMail_5]
#        include:
#          # macos-11 is a private preview on Github Actions
#          - os: macos-11
#            gpgmail: GPGMail_5


    steps:
      - uses: actions/checkout@v2
      - name: Make
        working-directory: Source
        run: |
          export COMMIT_HASH=${GITHUB_SHA:0:7}
          export BUILD_NUMBER=$(( $(date +"%s") / 3600 - 262968 ))
          export BUILD_VERSION=${BUILD_NUMBER}.${GITHUB_RUN_NUMBER}
          make ${{ matrix.gpgmail }}
      - name: Upload mailbundle
        uses: actions/upload-artifact@v2
        with:
          name: Free-${{ matrix.gpgmail }}.mailbundle
          path: Source/bundles/
