name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[no-build]')"

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: Source
      run: make
    # https://github.com/actions/upload-artifact/issues/76
    - name: zip artifacts
      working-directory: Source
      run: zip -r GPGMail_mailbundles.zip GPGMail_*.mailbundle
    - name: Upload mailbundles
      uses: actions/upload-artifact@v2
      with:
        name: GPGMail_mailbundles.zip
        path: Source/GPGMail_mailbundles.zip

        
